semgrep/semgrep-vscode

src/cli.ts
For my use case, having multiple rule sets like `semgrep --config "p/ci" --config "p/jwt"` show errors in VS Code would be great. Right now I need to go to the CLI and run all the rulesets, or toggle between different ones in the settings.json for my project. 
This change allows a `rules` setting to include as many URLs/paths as needed and passes each as a `--config` argument.
=> Config: comma-separated list of rule sets in addition to single paths

package-lock.json, package.json, src/constants.ts, src/lsp.ts
Add a CLI version check, and don't load the extension if it's an older semgrep version. I tried seeing what it takes to be backwards compatible, but the tech debt doesn't feel worth it. We'd have to have dynamic settings and commands based on the version, which feels gross to me.
=> Add CLI version check

package.json, src/env.ts, src/lsp.ts
Send the cool telemetry metrics VSCode gives us to the cli so we can report them.
=> Send metrics to semgrep-cli

.vscode/launch.json, .vscode/tasks.json, CHANGELOG.md, package.json, src/commands.ts, src/env.ts, src/extension.ts, src/lsp.ts, src/statusBar.ts
Added command to restart lsp. Also fixed issue where diagnostics were not rendering markdown. For development, we now will properly watch + reload extension source code when running debugger.
Just manually checked
PR checklist:
=> Add restart command

src/lsp.ts
Added `process.env` back to env_vars (as is default - https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback), ensuring we respect important environment variables such as `REQUESTS_CA_BUNDLE` - hopefully fixing #62.
PR checklist:
=> respect local env vars

package.json
This PR adds in support on the VS Code side, to be able to display the closest Generic AST node upon hover.
Companion to https://github.com/returntocorp/semgrep/pull/8142
PR checklist:
- [] Documentation is up-to-date
- [] A changelog entry was for any user-facing change
=> feat: hover for ast viewing

src/lsp.ts
Previously, the configuration object was not being converted to an object, so really it was dict like type, so when we set the metrics field it never was sent to the language server :/. This fixes that.
Check the output tab to verify these metrics are being sent
PR checklist:
=> fix: Typescript is bad at types

src/lsp.ts
Reverts returntocorp/semgrep-vscode#68
This breaks things really bad. I have no idea why but diagnostic reporting becomes absolutely trashed :/.
=> Revert "fix: Typescript is bad at types"

README.md
We've updated to use Policies in Semgrep Code rather than Rule board - this gets the README up to date with the change.
PR checklist:
=> Rule board -> Policies

src/lsp.ts
This makes it so it's easy to use the osemgrep binary directly for debugging purposes
PR checklist:
=> better debug option

src/showAstDocument.ts
This PR opens up the "Generic AST" feature of the extension as a different path.
This will make it so users cannot erroneously save the Generic AST as their real file.
Opened it up under the same file name, but appended with `.semgrep_ast.ml`.
Regrettably, we need the `.ml` or else the resulting Generic AST (which is just a dump of OCaml code) will not be highlighted nicely.
Tried it manually, and it opened under a different name.
Closes PDX-136
PR checklist:
=> chore: open generic ast under different name

package.json, src/lsp.ts
This PR adds the extension changes needed to be able to run the Pro Engine from the language server (via toggle).
It would be neat if people could do pro scans via the LS, and not be restricted solely to the OSS engine.
Made a toggle which changes the settings given to the `semgrep` entry point. That script takes care of all of the targeting logic, provided that the user has already done `semgrep install-semgrep-pro`.
Currently just for pro intrafile, because interfile scans would likely be too intensive for an IDE.
Paired with https://github.com/semgrep/semgrep/pull/9146:
for the rule
```
rules:
- id: my-other-cool-custom-rule
pattern-sources:
- pattern: |
source()
pattern-sinks:
- pattern: |
sink(...)
mode: taint
message: Semgrep found a match
languages: [python]
severity: WARNING
``` …
=> feat: intrafile scanning using Pro Engine

.github/workflows/bump-version.yaml
Allows us to automate PR-ing the repo when a new version of Semgrep is released
=> add bump-version workflow

package.json, src/commands.ts, src/interface/commands.ts, src/lspExtensions.ts, src/searchResultsTree.ts, src/views/search.ts, src/webview-ui/App.tsx
This is a stacked diff whose parent is https://github.com/semgrep/semgrep-vscode/pull/100.
This PR adds autofix functionality to the new UI. In particular, it adds a place to write the new autofix, and a replace all button.
Closes CDX-276
Closes CDX-274
PR checklist:
=> feat: autofix in new search UI

media/global.css, src/interface/interface.ts, src/lspExtensions.ts, src/views/webview.ts, src/webview-ui/src/components/TopSection/MainInputs.tsx, src/webview-ui/src/components/TopSection/TopSection.module.css, src/webview-ui/src/components/TopSection/TopSection.tsx, src/webview-ui/src/components/utils/TextBox.tsx, src/webview-ui/src/hooks/useStore.ts
This PR adds a UI for includes/excludes boxes, as well as doing a fairly major refactoring of our UI to make some things nicer.
The main things done were:
- introduction of `TextBox` for generic text inputs
- addition of a `...` which reveals and hides the includes/excludes boxes
- a more streamlined state API with the `useStore.ts` hook file, which gives us hooks that let us maintain the state of the webview
- persistent state of the patterns/fixes/whatever in the webview, by using local storage
PR checklist:
=> feat: includes/excludes

package-lock.json, package.json, src/webview-ui/src/components/SearchResults/EntryHeader.tsx, src/webview-ui/src/components/SearchResults/SearchResultEntry.tsx, src/webview-ui/src/components/SearchResults/SearchResults.module.css, yarn.lock
This is a stacked diff whose parent is #104.
This PR adds a chevron to the left of each file's matches, which lets you collapse the matches. It also adds a badge with the number of matches per file to the right.
Tested manually.
Closes CDX-286
PR checklist:
=> feat: collapsing matches and match number badges

src/commands.ts, src/interface/interface.ts, src/searchResultsTree.ts, src/utils.ts, src/views/webview.ts, src/webview-ui/src/components/SearchResults/SearchResults.module.css, src/webview-ui/src/components/SearchResults/SearchResults.tsx
This is a stacked diff whose parent is #106.
This PR adds a button which applies all non-applied fixes.
Tested manually.
PR checklist:
=> feat: fix all button

src/commands.ts, src/env.ts, src/interface/interface.ts, src/lspExtensions.ts, src/search.ts, src/searchResultsTree.ts, src/views/webview.ts, src/webview-ui/App.tsx, src/webview-ui/src/components/SearchResults/SearchResults.tsx, src/webview-ui/src/components/TopSection/TopSection.tsx, src/webview-ui/src/types/results.ts, src/webview-ui/src/types/state.ts, src/webview-ui/utilities/vscode.ts
This is a stacked diff whose parent is #107.
This PR introduces the capability to do streaming search, returning results as we get them.
This is facilitated via continuous communication between webview <-> extension <-> LSP. 
https://github.com/semgrep/semgrep/pull/9933 establishes a protocol that the extension may start an ongoing search with it, and then hit it with `/semgrep/searchOngoing` requests to continually get results out of it.
The extension spawns an asynchronous operation on each new search, whose job is to keep itself alive in a tight loop, constantly querying the LSP and sending the partial results back to the webview. These async threads terminate themselves when a new search is started. 
The webview is responsible for starting searches, and maintains an internal state of …
=> feat: streaming search

src/searchResultsTree.ts, src/views/webview.ts, src/webview-ui/App.css, src/webview-ui/src/components/SearchResults/SearchResults.module.css, src/webview-ui/src/components/TopSection/TopSection.tsx
Removes extra padding from the webview UI.
`setSearchItems` has a type error (or did for me), and I think it's unused, so I commented it out
PR checklist:
=> fix(webview): remove extra padding

CHANGELOG.md, package-lock.json, package.json, src/env.ts, src/extension.ts, src/lsp.ts, src/telemetry/sentry.ts, src/telemetry/telemetry.ts
We should now send a bunch of useful info to sentry when we crash, including the crash output from Semgrep! We will also include what settings were set.
PR checklist:
=> chore: add a bunch of sentry stuff

package.json, src/env.ts
PR checklist:
This creates a context key, which we can consume in a variety of places
to determine if we should enable some feature (See
<https://code.visualstudio.com/api/references/when-clause-contexts>).
For instance, an updated walkthrough could make use of this, and we can
use it to choose what views to show at the vscode level too.
=> feat: `loggedIn` context key
