- src/commands.ts
> Small login fix

- src/commands.ts
- src/lsp.ts
> Fixed error when semgrep not installed

- .vscode/extensions.json
- LICENSE
- TODO.md
- semgrep-vscode.code-workspace
> Add license (and clean up some things)

- README.md
> Simplify installation steps, move local Semgrep installation to prerequisites, add Search by pattern documentation

- README.md
> Minor readme edit

- CHANGELOG.md
- package.json
- src/env.ts
- src/extension.ts
- src/lsp.ts
Test plan:
Running the extension in development mode will prompt you once.
PR checklist:
> add prompt on new install

- CHANGELOG.md
- README.md
- package.json
> Version bump

- package.json
- src/lsp.ts
> Fix metrics

- .gitignore
- .vscode/launch.json
- download-lspjs.sh
- package-lock.json
- package.json
- semgrep-version
- src/commands.ts
- src/lsp.ts
> feat: lsp.js!

- .github/workflows/tests.yml
- package-lock.json
- package.json
- src/commands.ts
- src/extension.ts
- src/lsp.ts
- src/test/fixtures/test.py
- src/test/runTest.ts
- src/test/suite/basic.test.ts
- src/test/suite/index.ts
> VSCode e2e testing

- package.json
> Add vscode-languageserver

- CHANGELOG.md
- README.md
* Updated usage instructions
* Updated configuration options and commands information to reflect what's current
* General text edits; minor reorg of content
PR checklist:
> update README to reflect changes to the extension

- .github/workflows/tests.yml
- src/extension.ts
- src/test/runTest.ts
- src/test/suite/basic.test.ts
> maybe fix tests

- .eslintignore
- eslint.config.js
- src/env.ts
- src/lsp.ts
- src/test/runTest.ts
- src/test/suite/basic.test.ts
> Fix progress bars

- .github/workflows/lint.yaml
- .pre-commit-config.yaml
- package.json
- src/commands.ts
- src/env.ts
- src/extension.ts
- src/lsp.ts
- src/lspExtensions.ts
- src/searchResultsTree.ts
- src/statusBar.ts
- src/test/runTest.ts
- src/test/suite/basic.test.ts
- src/utilities/getUri.ts
- src/utils.ts
- src/views/search.ts
- src/webview-ui/index.tsx
Reverts semgrep/semgrep-vscode#129
> Revert "bump pre-commit???"

- package-lock.json
- package.json
- src/commands.ts
- src/interface/interface.ts
- src/views/webview.ts
- src/webview-ui/src/components/SearchResults/MatchItem.tsx
- src/webview-ui/src/components/SearchResults/MatchItemButtons.tsx
- src/webview-ui/src/components/SearchResults/SearchResultEntry.tsx
- src/webview-ui/src/components/SearchResults/SearchResults.module.css
- src/webview-ui/src/types/results.ts
- yarn.lock
This is a stacked diff whose parent is #105 .
This PR adds individual replace/dismiss buttons to each individual match item, which disappear when either is clicked.
Tested manually.
PR checklist:
> feat: replace/dismiss buttons

- .pre-commit-config.yaml
- src/commands.ts
- src/extension.ts
- src/interface/interface.ts
- src/lsp.ts
- src/lspExtensions.ts
- src/search.ts
- src/statusBar.ts
- src/test/runTest.ts
- src/test/suite/basic.test.ts
- src/utilities/getUri.ts
- src/utils.ts
- src/views/webview.ts
- src/webview-ui/index.tsx
- src/webview-ui/src/components/SearchResults/SearchResultEntry.tsx
- src/webview-ui/src/components/TopSection/MainInputs.tsx
- src/webview-ui/src/components/TopSection/MatchesSummary.tsx
- src/webview-ui/src/components/TopSection/PatternList.tsx
- src/webview-ui/src/hooks/useStore.ts
> Pre-commit

- package.json
https://github.com/semgrep/semgrep-vscode/actions/runs/8824309092/job/24226512885
@types/vscode and engine.vscode need to be the same apparently
PR checklist:
> bump engine

- CHANGELOG.md
- src/constants.ts
- src/lsp.ts
- src/utils.ts
> fix: properly check for updates

- .gitignore
- CHANGELOG.md
- build.mjs
- package-lock.json
- package.json
- src/extension.ts
- src/lsp.ts
- src/lspExtensions.ts
- src/telemetry/sentry.ts
- src/telemetry/telemetry.ts
Can be merged regardless of https://github.com/semgrep/semgrep-proprietary/pull/1678, but see it for more context
PR checklist:
> fix: Better error handling

- CHANGELOG.md
- README.md
> make minor edits to README for accuracy

- .github/workflows/publish.yaml
- .vscodeignore
- package.json
Apparently the gha we use to publish the VSCE has a bug :/. This fixes that.
PR checklist:
> fix publish issue

- CHANGELOG.md
- README.md
- package.json
- walkthrough/3-support.md
> chore: replace returntocorp with semgrep in URLs
